# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-viralrecon-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - hcc
dependencies:
  ## conda-forge packages
  - conda-forge::python=3.6.10
  - conda-forge::markdown=3.2.2
  - conda-forge::pymdown-extensions=7.1
  - conda-forge::pygments=2.6.1
  - conda-forge::pigz=2.3.4
  - conda-forge::r-base=3.6.2
  - conda-forge::bc=1.07.1

  ## bioconda packages
  ## common
  - bioconda::fastqc=0.11.9
  - bioconda::parallel-fastq-dump=0.6.6
  - bioconda::sra-tools=2.10.3
  - bioconda::fastp=0.20.1
  - bioconda::samtools=1.9
  - bioconda::bedtools=2.29.2
  - bioconda::multiqc=1.8

  ## variants
  - bioconda::bowtie2=2.3.5.1
  - bioconda::picard=2.22.8
  - bioconda::ivar=1.2.2
  - bioconda::bcftools=1.9
  - bioconda::varscan=2.4.4
  - bioconda::snpeff=4.5covid19
  - bioconda::snpsift=4.3.1t

  ## assembly
  - bioconda::cutadapt=2.10
  - bioconda::kraken2=2.0.9beta
  - bioconda::spades=3.14.0
  - bioconda::unicycler=0.4.7
  - bioconda::minia=3.2.3
  - bioconda::minimap2=2.17
  - bioconda::seqwish=0.4.1
  - bioconda::vg=1.24.0
  - bioconda::quast=5.0.2
  - bioconda::blast=2.9.0
  - bioconda::plasmidid=1.5.2
  - bioconda::bandage=0.8.1
  - hcc::abacas=1.3.1
